export const CAT_EVENT_AGGREGATE = 'CAT';
export const CAT_CREATED_EVENT_TYPE = 'CAT_CREATED';
export const CAT_DELETED_EVENT_TYPE = 'CAT_DELETED';
export const CAT_UPDATED_EVENT_TYPE = 'CAT_UPDATED';
